export const englishStrings = {
  login: 'Login',
  companyIdPlaceholder: 'Company ID',
  companyIdErrorMessage: 'Please enter a valid Company ID.',
  emailPlaceholder: 'Email',
  emailErrorMessage: 'Please enter a valid email ID.',
  passwordPlaceholder: 'Password',
  passwordErrorMessage: 'Please enter a valid password.',
  accountNotRegistered: "Don't have an account? Register",
  register: 'Register',
  namePlaceholder: 'Name', 
  nameErrorMessage: 'Please enter a valid name.', 
  selectGender: 'Select Gender',
  registerButton: 'Register',
  haveAccount: 'Already have an account? Login',
  warning: 'Warning',
  enterVehicleId: 'Please enter a valid vehicle ID.',
  enterVehicleIdPrompt: 'Please enter your vehicle ID.',
  vehicleIdPlaceholder: 'Vehicle ID',
  start: 'Start',
  submit: 'Submit',
  reasonHeading: 'Reason',
  submitWithReason: 'Submit with Reason',
  reasonPlaceholder: 'Enter Reason',
  selectDataPlaceholder: 'Select Data',
  vehicleIdHeader: 'Vehicle ID',
  vehicleIdPlaceholder: 'Vehicle ID',
  profile: 'Profile',
  contact: 'Contact Us',
  termsAndConditions: 'Terms & Conditions',
  privacyPolicy: 'Privacy Policy',
  deleteAccount: 'Delete Account',
  logout: 'Logout',
  profile: 'Profile',
  takePhoto: 'Take Photo',
  chooseFromGallery: 'Choose from Gallery',
  cancel: 'Cancel',
  contact: 'Contact',
  termsAndConditions: 'Terms & Conditions',
  privacyPolicy: 'Privacy Policy',
  deleteAccount: 'Delete Account',
  logout: 'Logout',
  alert_warning: "Warning",
  alert_description: "Please enter correct details.",
  gender_male: "Male",
  gender_female: "Female",
  gender_other: "Other",
  alert_warning: "Warning",
  alert_button_okay: "Okay",
  alert_button_cancel: "Cancel",
  alert_button_add_comment: "Add Comment",
  alert_enter_vehicle_id: "Please enter the vehicle ID.",
  alert_add_comment_description: "Some fields are unchecked. Please add a reason and then submit.",
  alert_success: "Success",
  alert_submit_success: "Submitted successfully",
  alert_button_okay: "Okay",
  alert_error: "Error",
  alert_delete: "Delete",
  alert_button_okay: "Okay",
  alert_button_cancel: "Cancel",
  alert_button_delete: "Delete",
  alert_button_yes: "Yes",
  alert_delete_account_confirmation: "Are you sure you want to delete this account?",
  alert_logout_confirmation: "Are you sure you want to logout?",
  camera_permission_title: "Camera Permission",
  camera_permission_message: "The app needs access to your camera to take photos.",
  camera_permission_allow: "Allow",
  camera_permission_cancel: "Cancel",
  change_language : "Change language",
  
};
