export const hindiStrings = {
  login: 'लॉगिन',
  companyIdPlaceholder: 'कंपनी आई डी',
  companyIdErrorMessage: 'कृपया उचित कंपनी आई डी डालें |',
  emailPlaceholder: 'ईमेल',
  emailErrorMessage: 'कृपया उचित ईमेल आईडी डालें |',
  passwordPlaceholder: 'पासवर्ड',
  passwordErrorMessage: 'कृपया उचित पासवर्ड डालें |',
  accountNotRegistered: 'अकाउंट नहीं है? रजिस्टर',
  register: 'रजिस्टर',
  namePlaceholder: 'नाम',
  nameErrorMessage: 'कृपया उचित नाम डालें |',
  selectGender: 'लिंग चुनें',
  registerButton: 'रजिस्टर',
  haveAccount: 'पहले से अकाउंट है? लॉगिन',
  warning: 'चेतावनी',
  enterVehicleId: 'वाहन आईडी दर्ज करें।',
  enterVehicleIdPrompt: 'कृपया अपने वाहन आईडी दर्ज करें।',
  vehicleIdPlaceholder: 'वाहन आईडी',
  start: 'शुरू करें',
  submit: 'जमा करें',
  reasonHeading: 'कारण',
  submitWithReason: 'कारण के साथ जमा करें',
  reasonPlaceholder: 'कारण दर्ज करें',
  selectDataPlaceholder: 'डेटा चुनें',
  vehicleIdHeader: 'वाहन आईडी',
  vehicleIdPlaceholder: 'वाहन आईडी',
  profile: 'प्रोफाइल',
  takePhoto: 'तस्वीर लें।',
  chooseFromGallery: 'गैलरी से चुनाव करें।',
  cancel: 'निरस्त करें।',
  contact: 'संपर्क करें।',
  termsAndConditions: 'नियम व शर्तें।',
  privacyPolicy: 'प्राइवेसी पॉलिसी।',
  deleteAccount: 'खाता डिलीट करें।',
  logout: 'लागआउट करें।',
  alert_warning: "चेतावनी",
  alert_description: "कृपया सही विवरण दर्ज करें।",
  gender_male: "पुरुष",
  gender_female: "महिला",
  gender_other: "अन्य",
  alert_warning: "चेतावनी",
  alert_button_okay: "ठीक है",
  alert_button_cancel: "रद्द करें",
  alert_button_add_comment: "कारण जोड़ें",
  alert_enter_vehicle_id: "कृपया वाहन आईडी दर्ज करें।",
  alert_add_comment_description: "कुछ फ़ील्ड अचयनित हैं। कृपया कारण जोड़ें और फिर सबमिट करें।",
  alert_success: "सफलता",
  alert_submit_success: "सफलतापूर्वक सबमिट किया गया",
  alert_button_okay: "ठीक है",
  alert_error: "एरर",
  alert_delete: "हटाएँ",
  alert_button_okay: "ठीक है",
  alert_button_cancel: "रद्द करें",
  alert_button_delete: "हटाएँ",
  alert_button_yes: "हाँ",
  alert_delete_account_confirmation: "क्या आप इस अकाउंट को हटाना चाहते हैं?",
  alert_logout_confirmation: "क्या आप वाकई लॉगआउट करना चाहते हैं?",
  camera_permission_title: "कैमरा अनुमति",
  camera_permission_message: "ऐप को फोटो लेने के लिए आपके कैमरे तक पहुंच की आवश्यकता है।",
  camera_permission_allow: "अनुमति दें",
  camera_permission_cancel: "रद्द करें",
  change_language :"भाषा बदलें।"
 
};
